package com.example.oneclickherblore;

public enum OneClickHerblorePots {
    attack,
    antipoison,
    strength,
    compost,
    ultra_compost,
    energy,
    agility,
    prayer,
    super_attack,
    super_antipoison,
    super_energy,
    super_strength,
    super_restore,
    super_defence,
    antidote_p,
    antifire,
    ranging,
    magic,
    stamina,
    antidote_pp,
    brew,
    extended_antifire,
    antivenom,
    //super_combat,
    antivenom_p,
    extended_super_antifire
}
